spring:
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  datasource:
    url: jdbc:oracle:thin:@192.168.1.110:1521:jhmesv101
    username: jh
    password: zzz
    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@192.168.13.112:1521:orcl
#    username: jh
#    password: jh
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:sqlserver://192.168.1.103:1433;databaseName=activiti
#    username: sa
#    password: zzz
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  activiti:
    checkProcessDefinitions: false
    asyncExecutorActivate: false
#  jpa:
#    database: sql_server
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.SQLServer2008Dialect
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  devtools:
    restart:
      enable: false
#  resources:
#    static-locations: classpath:/static
#  mvc:
#    static-path-pattern: /static

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.jh.entity
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.jh.dao: DEBUG

#pagehelper
pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#activiti
purchasingProcessDefinitionKey: flowAudit
purchasingStartTaskKey: createOrder